---
# Tasks for storage account configuration

- name: Create file share directories
  file:
    path: "{{ item.path }}"
    state: directory
    group: "{{ item.group | lower }}"
    mode: "{{ item.directory_mask }}"
  when: item.path != ""
  with_items:
    - "{{ file_shares }}"