---
# Tasks for ubuntu

- name: Make sure all packages are up-to-date
  apt:
    name: "*"
    state: latest
- name: Install Samba (SMB) and net-tools
  apt:
    name: ["samba", "net-tools"]
    state: present
- name: Create users on Samba user management system (append)
  shell: (echo {{ item.default_password }}; echo {{ item.default_password }}) | smbpasswd -a {{ item.name }}
  with_items:
    - "{{ user_list }}"
- name: Template smb.conf
  template:
    src: "{{ role_path }}/templates/smb.conf.j2"
    dest: /etc/samba/smb.conf
    force: true
- name: Make sure smbd is enabled at startup
  systemd:
    name: smbd
    enabled: true
- name: Restart the smbd service
  systemd:
    name: smbd
    state: restarted