---
# Tasks for setting up users

- name: Add groups from config (if not exists)
  group:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ group_list }}"

- name: Add users from config (if not exists)
  user:
    name: "{{ item.name }}"
    shell: "{{ item.shell }}"
    password: "{{ item.default_password }}"
    groups: "{{ item.groups }}"
    create_home: yes
    append: yes
  with_items:
    - "{{ user_list }}"
